### ISSUE TITLE
rhel8cis_firewall_interface should be variable

### ISSUE THREAD

**Issue by aaosopra** [ansible-lockdown/RHEL8-CIS-Audit#57]
**Feature Request or Enhancement:**

- Feature [ Change rhel8cis_firewall_interface in ansible_vars_goss.yml.j2 to take variable]
- Enhancement [Not everyone uses enp0s3 or enp0s8 network interface]

**Summary of Request**
Want to be able to control which network interfaces goss tests for.
Only allowing  enp0s3 or enp0s8 creates false negatives

**Describe alternatives you've considered**
Disable the whole test

**Suggested Code**

in ansible_vars_goss.yml.j2:

`rhel8cis_firewall_interface: {{  rhel8cis_firewall_interfaces }}`

in defaults/main.yml

`  rhel8cis_firewall_interfaces: {{ ansible_default_ipv4.interface }} `

**Comment by uk-bolly** [comment]
hi @aaosopra 

Apologies for the delay on this one. There has been a few changes to the baseline since this was opened and the interface is no longer set in the firewall rules.
This also raises the question this should be raised again the audit or remediate repository so we can track the correct branch and details you are referring too,.
Again sorry we have missed this one, i will close but if if you feel this is still an issue please let us know.

regards

uk-bolly
